// This file has been autogenerated from a class added in the UI designer.

using System;
using GroceriesiOSCS.Classes;
using GroceriesiOSCS.Classes.DataManagement;
using GroceriesiOSCS.Classes.Helpers;
using GroceriesiOSCS.Models;
using UIKit;

namespace GroceriesiOSCS
{
	public partial class ItemsViewController : UIViewController
    {
        public GroceryList currentList;
        ItemsDataSource itemsDataSource;
        
		public ItemsViewController(IntPtr handle) : base(handle)
		{
		}

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            listNameLabel.Text = currentList.ListName;
            
            itemsDataSource = new ItemsDataSource (currentList);
            itemsTableView.Source = itemsDataSource;

            itemTextField.ReturnKeyType = UIReturnKeyType.Done;
            itemTextField.ShouldReturn += MakeNewItem;
        }

        bool MakeNewItem (UITextField textfield)
        {
            var name = textfield.Text;
            textfield.ResignFirstResponder ();
            textfield.Text = "";

            var newItem = new Item {
                ItemName = name,
                ItemTime = DateTime.Now,
                ItemPurchased = false
            };
            
            currentList.ListItems.Add (newItem);
            itemsTableView.ReloadData ();
            
            ReadWriteDisk.WriteData ();
            CloudFunctions.SaveItem (newItem, currentList);
            
            return true;
        }

        partial void BackButton_TouchUpInside(UIButton sender)
        {
            DismissViewController(true, null);
        }

        partial void ShareList_TouchUpInside(UIButton sender)
        {
            if (AppData.auth.CurrentUser == null)
                CustomAlert.Alert (this, "Offline", "Please login first.");

            var alert = UIAlertController.Create ("Inviting Someone?", "Please enter their email", UIAlertControllerStyle.Alert);
            alert.AddTextField (field => {
                field.Placeholder = "email address";
                field.Font = UIFont.SystemFontOfSize (22);
                field.TextAlignment = UITextAlignment.Center;
            });
            
            alert.AddAction (UIAlertAction.Create ("Invite", UIAlertActionStyle.Default, action => {
                InviteSomeone.Invite (this, currentList, alert.TextFields[0].Text);
            }));
            
            alert.AddAction (UIAlertAction.Create ("Cancel", UIAlertActionStyle.Cancel, null));

            PresentViewController (alert, true, null);

        }
    }
}
